In [11]:
import numpy as np
import pandas as pd

df_train = pd.read_csv('/home/dgxuser40/manjil/finsurv/participant_data/Borrow/Deposit/train.csv')
df_test = pd.read_csv('/home/dgxuser40/manjil/finsurv/participant_data/Borrow/Deposit/test_features.csv')

In [12]:
df_train.head(3)

,userBorrowSum,marketWithdrawAvgAmount,marketDepositAvgAmountUSD,sinDayOfMonth,userSecondsSinceFirstTransaction,timeOfDay,userActiveDaysWeekly,userLiquidationCount,userActiveDaysMonthly,userRepayCount,...,userBorrowAvgAmountUSD,userReserveMode,userSecondsSincePreviousTransaction,marketBorrowSumUSD,userRepaySum,logAmountUSD,marketDepositCount,marketRepayAvgAmountUSD,sinQuarter,marketLiquidationAvgAmount
0,0.20000,1.999000,1.199348,-0.207912,3185.0,8.832500,1.0,0,1.0,0,...,0.199924,DAI,3185.0,1.199815,0.0,0.182258,9.0,0.0,1.0,0.0
1,0.79299,1.999000,7.933243,-0.207912,328.0,11.998333,1.0,0,1.0,0,...,0.793127,DAI,328.0,7.992995,0.0,0.583961,13.0,0.0,1.0,0.0
2,1.00000,1.003755,965.952496,-0.207912,236.0,12.476111,1.0,0,1.0,0,...,0.999869,USDC,236.0,9.000794,0.0,0.693082,29.0,0.0,1.0,0.0

In [13]:
# df_train.keys()

In [14]:
df_test.head(3)

,userBorrowSum,marketWithdrawAvgAmount,marketDepositAvgAmountUSD,sinDayOfMonth,userSecondsSinceFirstTransaction,timeOfDay,userActiveDaysWeekly,userLiquidationCount,userActiveDaysMonthly,userRepayCount,...,userBorrowAvgAmountUSD,userReserveMode,userSecondsSincePreviousTransaction,marketBorrowSumUSD,userRepaySum,logAmountUSD,marketDepositCount,marketRepayAvgAmountUSD,sinQuarter,marketLiquidationAvgAmount
0,8.949265e+03,2867.140612,6276.512716,-0.994522,16667973.0,18.471389,1.0,5,1.0,129,...,22.733882,USDT,40.0,3.955663e+08,7.356789e+03,2.091651,100710.0,10263.005857,-1.000000e+00,1018.125824
1,1.805657e+06,141133.067726,128446.084615,0.951057,93565059.0,18.206389,7.0,129,30.0,1656,...,148.980910,USDC,30.0,3.569418e+07,1.384321e+06,2.079407,100005.0,2308.695749,1.224647e-16,547.651451
2,4.562744e+05,18824.250331,34411.606443,-0.406737,23417942.0,18.690833,1.0,0,5.0,6,...,27475.761041,DAI,691881.0,8.554781e+07,1.820250e+05,9.903921,74008.0,3586.687836,1.000000e+00,820.023849

In [15]:
# Borrow-to-Deposit ratio
df_train['borrow_to_deposit'] = np.where(df_train['userDepositSum'] > 0,
                                   df_train['userBorrowSum'] / df_train['userDepositSum'], 0)

# Liquidation-to-Borrow ratio
df_train['liquidation_to_borrow'] = np.where(df_train['userBorrowSum'] > 0,
                                       df_train['userLiquidationSum'] / df_train['userBorrowSum'], 0)

# Repay-to-Borrow ratio
df_train['repay_to_borrow'] = np.where(df_train['userBorrowSum'] > 0,
                                 df_train['userRepaySum'] / df_train['userBorrowSum'], 0)

# clean up infinities and NaNs
df_train.replace([np.inf, -np.inf], 0, inplace=True)
df_train.fillna(0, inplace=True)

In [16]:
print(df_train[['borrow_to_deposit', 'liquidation_to_borrow', 'repay_to_borrow']].head())

   borrow_to_deposit  liquidation_to_borrow  repay_to_borrow
0           0.200000                    0.0              0.0
1           0.079299                    0.0              0.0
2           0.200000                    0.0              0.0
3           0.283019                    0.0              0.0
4          29.453109                    0.0              0.0

In [17]:
df_train.columns[-3:]  # should show the newly added ratio columns

Index(['borrow_to_deposit', 'liquidation_to_borrow', 'repay_to_borrow'], dtype='object')