In [2]:
# --- import libraries ---
import pandas as pd
import numpy as np
import os
import shutil
from lifelines import CoxPHFitter
from lifelines.exceptions import ConvergenceError
from sklearn.preprocessing import StandardScaler
from typing import Tuple, Optional
import matplotlib.pyplot as plt
import seaborn as sns

PARTICIPANT_DATA_PATH = './participant_data/'

In [3]:
from utilities.preprocess import preprocess

index_event = "Borrow"
outcome_event = "Liquidated"
dataset_path = os.path.join(index_event, outcome_event)

train_df = pd.read_csv(os.path.join(PARTICIPANT_DATA_PATH, dataset_path, 'train.csv'))
test_features_df = pd.read_csv(os.path.join(PARTICIPANT_DATA_PATH, dataset_path, 'test_features.csv'))

X_train, y_train, X_test_processed = preprocess(train_df, test_features_df)

lifelines_train_df = pd.concat([X_train, y_train.reset_index(drop=True)], axis=1)

In [5]:
y_train

          timeDiff  status
0       75264503.0     0.0
1       75091115.0     0.0
2       75084884.0     0.0
3       75084844.0     0.0
4       75079718.0     0.0
...            ...     ...
885903    185341.0     1.0
885904    423199.0     1.0
885905    230107.0     1.0
885906    228037.0     1.0
885907   1129447.0     1.0

[885908 rows x 2 columns]

In [3]:
lifelines_train_df.head()

,userBorrowSum,marketWithdrawAvgAmount,marketDepositAvgAmountUSD,sinDayOfMonth,userSecondsSinceFirstTransaction,timeOfDay,userActiveDaysWeekly,userLiquidationCount,userActiveDaysMonthly,userRepayCount,...,userSecondsSincePreviousTransaction,marketBorrowSumUSD,userRepaySum,logAmountUSD,marketDepositCount,marketRepayAvgAmountUSD,sinQuarter,marketLiquidationAvgAmount,timeDiff,status
0,-0.398558,-2.489321,-2.099994,0.289315,-0.785666,-0.570639,-0.396655,-0.156334,-0.892979,-0.402879,...,-0.079284,-1.733569,-0.398471,-1.254174,-1.577749,-2.370232,1.542022,-0.932965,75264503.0,0.0
1,-0.398558,-2.487828,-2.099970,-0.306477,-0.797257,-0.545239,-1.190754,-0.156334,-1.072193,-0.402879,...,-0.130458,-1.733569,-0.398471,-1.382937,-1.577674,-2.370232,1.542022,-0.932965,75091115.0,0.0
2,-0.398558,-2.487828,-2.097217,-0.306477,-0.797492,-0.276081,-1.190754,-0.156334,-1.072193,-0.402879,...,-0.132896,-1.733569,-0.398471,-1.254154,-1.577637,-2.370232,1.542022,-0.932965,75084884.0,0.0
3,-0.398558,-2.487828,-2.097217,-0.306477,-0.797489,-0.274353,-1.190754,-0.156334,-1.072193,-0.402879,...,-0.133089,-1.733569,-0.398471,-0.977241,-1.577637,-2.370232,1.542022,-0.932965,75084844.0,0.0
4,-0.398558,-2.487828,-2.095696,-0.306477,-0.797487,-0.052927,-1.190754,-0.156334,-1.072193,-0.402879,...,-0.132848,-1.733569,-0.398471,-1.281682,-1.577600,-2.370232,1.542022,-0.932965,75079718.0,0.0

In [36]:
lifelines_train_df.shape

(885908, 80)

In [43]:
lifelines_train_df["status"].value_counts()
status_0_count = lifelines_train_df["status"].value_counts()[0]
status_1_count = lifelines_train_df["status"].value_counts()[1]

print(f"No of status=0: {status_0_count}")
print(f"No of status=1: {status_1_count}")

No of status=0: 861864
No of status=1: 24044

In [44]:
print(f"% of status=0: {status_0_count/(status_0_count + status_1_count):.2f}")
print(f"% of status=1: {status_1_count/(status_0_count + status_1_count):.2f}")

% of status=0: 0.97
% of status=1: 0.03

In [45]:
##-- First Oversample the minority class --##
import pandas as pd
from sklearn.utils import resample

# Separate majority and minority classes
df_majority = lifelines_train_df[lifelines_train_df['status'] == 0]
df_minority = lifelines_train_df[lifelines_train_df['status'] == 1]

# Over-sample minority class to match majority class size
df_oversampled = resample(df_minority,
                                   replace=True,                 
                                   n_samples=len(df_majority)//5,    
                                   random_state=42)              

# Combine majority class with oversampled minority class
df_balanced = pd.concat([df_majority, df_oversampled])

# Shuffle the dataset
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Balanced dataset shape: {df_balanced.shape}")
laundering_counts = df_balanced['status'].value_counts()
print(laundering_counts)
print(f"\nStatus 0 %: {laundering_counts[0] / (laundering_counts[0] + laundering_counts[1]) * 100:.2f}%")
print(f"Status 1 %: {laundering_counts[1] / (laundering_counts[0] + laundering_counts[1]) * 100:.2f}%")

Balanced dataset shape: (1034236, 80)
status
0.0    861864
1.0    172372
Name: count, dtype: int64

Status 0 %: 83.33%
Status 1 %: 16.67%

In [51]:
df_balanced.head()

,userBorrowSum,marketWithdrawAvgAmount,marketDepositAvgAmountUSD,sinDayOfMonth,userSecondsSinceFirstTransaction,timeOfDay,userActiveDaysWeekly,userLiquidationCount,userActiveDaysMonthly,userRepayCount,...,userSecondsSincePreviousTransaction,marketBorrowSumUSD,userRepaySum,logAmountUSD,marketDepositCount,marketRepayAvgAmountUSD,sinQuarter,marketLiquidationAvgAmount,timeDiff,status
0,-0.398509,1.695001,0.689370,-1.371254,-0.345753,0.613425,-0.793705,-0.156334,-0.803372,-0.402825,...,0.009835,2.109067,-0.398448,-0.056992,-0.758037,2.008346,-1.525506,-0.615704,58734692.0,0.0
1,-0.107327,0.378040,0.799263,1.354092,-0.693872,0.879344,1.191543,-0.156334,0.182305,0.216558,...,-0.133030,-0.359169,-0.107372,1.039942,0.641736,-0.902107,0.008258,0.137847,9826136.0,0.0
2,-0.398558,-0.833275,-1.143734,-0.591353,-0.556728,-1.026062,-0.793705,-0.156334,-0.713765,-0.402665,...,-0.132632,-0.119609,-0.398471,-1.404857,1.640600,-0.520144,0.008258,-0.589210,52893846.0,0.0
3,0.025070,1.015406,1.063875,-1.073358,-0.624595,0.763318,1.191543,-0.156334,1.078376,0.457364,...,-0.130977,-0.284800,0.024806,1.076725,0.465565,-0.847099,0.008258,1.210734,8964822.0,0.0
4,-0.398558,-0.861169,-1.211335,-1.433531,-0.403069,-0.560185,-0.793705,-0.156334,-0.713765,-0.402825,...,-0.132717,-0.416711,-0.398471,-1.426368,0.923210,-0.604234,0.008258,-0.565744,53401461.0,0.0

In [52]:
len(df_balanced["status"]), len(df_balanced["timeDiff"])

(1034236, 1034236)

In [53]:
model = CoxPHFitter(penalizer=0.1)
model.fit(df_balanced, duration_col='timeDiff', event_col='status')

In [54]:
model.print_summary()

<lifelines.CoxPHFitter: fitted with 1.03424e+06 total observations, 861864 right-censored observations>
             duration col = 'timeDiff'
                event col = 'status'
                penalizer = 0.1
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 1.03424e+06
number of events observed = 172372
   partial log-likelihood = -2268960.52
         time fit was run = 2025-09-20 11:44:04 UTC

---
                                     coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
userBorrowSum                       -0.10      0.91      0.00           -0.10           -0.09                0.90                0.91
marketWithdrawAvgAmount             -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
marketDepositAvgAmountUSD            0.04      1.04      0.00            0.03            0.04                1.03                1.04
sinDayOfMonth                        0.05      1.05      0.00            0.05            0.06                1.05                1.06
userSecondsSinceFirstTransaction     0.02      1.02      0.00            0.02            0.03                1.02                1.03
timeOfDay                            0.01      1.01      0.00            0.01            0.02                1.01                1.02
userActiveDaysWeekly                 0.19      1.21      0.00            0.19            0.19                1.20                1.22
userLiquidationCount                 0.19      1.20      0.00            0.18            0.19                1.20                1.21
userActiveDaysMonthly                0.12      1.13      0.00            0.11            0.12                1.12                1.13
userRepayCount                      -0.11      0.90      0.00           -0.12           -0.10                0.89                0.90
cosQuarter                           0.01      1.01      0.00            0.01            0.02                1.01                1.02
marketRepayAvgAmount                -0.01      0.99      0.00           -0.01           -0.00                0.99                1.00
marketLiquidationSum                 0.01      1.01      0.00            0.00            0.01                1.00                1.01
userLiquidationSum                   0.05      1.06      0.00            0.05            0.06                1.05                1.06
sinDayOfQuarter                      0.03      1.03      0.00            0.03            0.04                1.03                1.04
marketLiquidationCount               0.00      1.00      0.00           -0.00            0.01                1.00                1.01
userRepaySumUSD                     -0.10      0.91      0.00           -0.10           -0.09                0.90                0.91
userWithdrawCount                   -0.03      0.97      0.00           -0.03           -0.02                0.97                0.98
marketRepayCount                     0.03      1.03      0.00            0.03            0.04                1.03                1.04
userLiquidationSumUSD               -0.07      0.93      0.00           -0.07           -0.07                0.93                0.94
marketWithdrawSum                   -0.00      1.00      0.00           -0.01            0.01                0.99                1.01
userWithdrawSumUSD                  -0.04      0.96      0.00           -0.04           -0.03                0.96                0.97
marketBorrowSum                      0.00      1.00      0.00           -0.00            0.01                1.00                1.01
marketLiquidationAvgAmountUSD       -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userDepositSumUSD                   -0.04      0.96      0.00           -0.05           -0.03                0.96                0.97
quarter                             -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userBorrowAvgAmount                 -0.14      0.87      0.00           -0.15           -0.13                0.86                0.88
marketWithdrawCount                 -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
userRepayAvgAmount                  -0.11      0.89      0.00           -0.12           -0.11                0.89                0.90
dayOfQuarter                         0.02      1.02      0.00            0.01            0.02                1.01                1.02
cosDayOfQuarter                      0.02      1.02      0.00            0.01            0.02                1.01                1.02
userWithdrawSum                     -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
dayOfMonth                          -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
dayOfYear                           -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
marketDepositSumUSD                  0.01      1.01      0.00            0.00            0.02                1.00                1.02
userDepositSum                      -0.03      0.97      0.00           -0.04           -0.02                0.96                0.98
priceInUSD                           0.07      1.08      0.00            0.07            0.08                1.07                1.08
userLiquidationAvgAmountUSD          0.04      1.04      0.00            0.03            0.04                1.03                1.04
marketBorrowAvgAmount                0.04      1.04      0.00            0.03            0.04                1.03                1.04
userRepayAvgAmountUSD               -0.13      0.88      0.00           -0.13           -0.12                0.88                0.89
userWithdrawAvgAmountUSD            -0.09      0.92      0.00           -0.09           -0.08                0.91                0.92
userWithdrawAvgAmount               -0.06      0.94      0.00           -0.07           -0.06                0.93                0.95
marketBorrowCount                   -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
userActiveDaysYearly                 0.03      1.03      0.00            0.02            0.03                1.02                1.03
marketRepaySumUSD                   -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
userLiquidationAvgAmount             0.03      1.04      0.00            0.03            0.04                1.03                1.04
amount                              -0.10      0.91      0.00           -0.10           -0.09                0.90                0.91
marketDepositSum                    -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
amountUSD                           -0.12      0.89      0.00           -0.12           -0.11                0.88                0.89
marketBorrowAvgAmountUSD             0.02      1.02      0.00            0.02            0.03                1.02                1.03
marketWithdrawSumUSD                 0.01      1.01      0.00            0.01            0.02                1.01                1.02
marketDepositAvgAmount               0.02      1.02      0.00            0.01            0.02                1.01                1.02
userDepositAvgAmountUSD             -0.10      0.90      0.00           -0.11           -0.10                0.90                0.91
userBorrowCount                     -0.12      0.88      0.00           -0.13           -0.12                0.88                0.89
dayOfWeek                           -0.01      0.99      0.00           -0.01           -0.00                0.99                1.00
cosDayOfMonth                        0.00      1.00      0.00           -0.00            0.01                1.00                1.01
marketRepaySum                       0.00      1.00      0.00           -0.00            0.01                1.00                1.01
sinTimeOfDay                        -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userBorrowSumUSD                    -0.10      0.91      0.00           -0.10           -0.09                0.90                0.91
cosTimeOfDay                        -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
cosDayOfWeek                         0.01      1.01      0.00            0.01            0.02                1.01                1.02
marketWithdrawAvgAmountUSD          -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
marketLiquidationSumUSD             -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
userDepositAvgAmount                -0.06      0.94      0.00           -0.07           -0.05                0.93                0.95
sinDayOfYear                         0.01      1.01      0.00            0.01            0.02                1.01                1.02
userDepositCount                    -0.06      0.94      0.00           -0.07           -0.06                0.93                0.94
cosDayOfYear                        -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
logAmount                            0.07      1.07      0.00            0.06            0.07                1.07                1.08
sinDayOfWeek                         0.00      1.00      0.00            0.00            0.01                1.00                1.01
userBorrowAvgAmountUSD              -0.15      0.86      0.00           -0.16           -0.15                0.85                0.86
userSecondsSincePreviousTransaction -0.03      0.97      0.00           -0.04           -0.03                0.96                0.97
marketBorrowSumUSD                  -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
userRepaySum                        -0.10      0.91      0.00           -0.10           -0.09                0.90                0.91
logAmountUSD                         0.11      1.11      0.00            0.10            0.11                1.11                1.12
marketDepositCount                  -0.05      0.95      0.00           -0.05           -0.04                0.95                0.96
marketRepayAvgAmountUSD             -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
sinQuarter                           0.00      1.00      0.00           -0.00            0.01                1.00                1.01
marketLiquidationAvgAmount           0.00      1.00      0.00           -0.00            0.01                1.00                1.01

                                     cmp to      z      p  -log2(p)
covariate
userBorrowSum                          0.00 -30.09 <0.005    658.49
marketWithdrawAvgAmount                0.00  -9.59 <0.005     70.01
marketDepositAvgAmountUSD              0.00  13.33 <0.005    132.27
sinDayOfMonth                          0.00  24.37 <0.005    433.49
userSecondsSinceFirstTransaction       0.00  11.02 <0.005     91.47
timeOfDay                              0.00   6.30 <0.005     31.69
userActiveDaysWeekly                   0.00  80.56 <0.005       inf
userLiquidationCount                   0.00 202.88 <0.005       inf
userActiveDaysMonthly                  0.00  47.66 <0.005       inf
userRepayCount                         0.00 -34.64 <0.005    870.90
cosQuarter                             0.00   5.23 <0.005     22.52
marketRepayAvgAmount                   0.00  -2.57   0.01      6.63
marketLiquidationSum                   0.00   2.56   0.01      6.60
userLiquidationSum                     0.00  28.77 <0.005    602.07
sinDayOfQuarter                        0.00  14.61 <0.005    158.13
marketLiquidationCount                 0.00   1.91   0.06      4.15
userRepaySumUSD                        0.00 -30.38 <0.005    670.82
userWithdrawCount                      0.00  -8.56 <0.005     56.24
marketRepayCount                       0.00  12.85 <0.005    123.07
userLiquidationSumUSD                  0.00 -34.31 <0.005    854.35
marketWithdrawSum                      0.00  -0.08   0.94      0.09
userWithdrawSumUSD                     0.00 -12.87 <0.005    123.44
marketBorrowSum                        0.00   1.10   0.27      1.89
marketLiquidationAvgAmountUSD          0.00  -7.38 <0.005     42.54
userDepositSumUSD                      0.00 -13.14 <0.005    128.58
quarter                                0.00  -6.45 <0.005     33.02
userBorrowAvgAmount                    0.00 -44.24 <0.005       inf
marketWithdrawCount                    0.00  -1.53   0.13      2.98
userRepayAvgAmount                     0.00 -36.22 <0.005    952.08
dayOfQuarter                           0.00   7.65 <0.005     45.48
cosDayOfQuarter                        0.00   7.67 <0.005     45.72
userWithdrawSum                        0.00  -7.49 <0.005     43.68
dayOfMonth                             0.00  -1.53   0.13      2.99
dayOfYear                              0.00  -4.64 <0.005     18.11
marketDepositSumUSD                    0.00   3.57 <0.005     11.44
userDepositSum                         0.00  -9.98 <0.005     75.48
priceInUSD                             0.00  38.41 <0.005       inf
userLiquidationAvgAmountUSD            0.00  21.20 <0.005    328.92
marketBorrowAvgAmount                  0.00  12.89 <0.005    123.81
userRepayAvgAmountUSD                  0.00 -40.40 <0.005       inf
userWithdrawAvgAmountUSD               0.00 -28.30 <0.005    582.73
userWithdrawAvgAmount                  0.00 -19.08 <0.005    267.14
marketBorrowCount                      0.00  -7.79 <0.005     47.12
userActiveDaysYearly                   0.00  11.92 <0.005    106.43
marketRepaySumUSD                      0.00  -0.51   0.61      0.71
userLiquidationAvgAmount               0.00  22.06 <0.005    355.79
amount                                 0.00 -30.60 <0.005    680.50
marketDepositSum                       0.00  -1.22   0.22      2.17
amountUSD                              0.00 -37.63 <0.005   1027.02
marketBorrowAvgAmountUSD               0.00   8.67 <0.005     57.67
marketWithdrawSumUSD                   0.00   4.34 <0.005     16.07
marketDepositAvgAmount                 0.00   6.90 <0.005     37.49
userDepositAvgAmountUSD                0.00 -32.88 <0.005    785.44
userBorrowCount                        0.00 -39.03 <0.005       inf
dayOfWeek                              0.00  -2.57   0.01      6.62
cosDayOfMonth                          0.00   1.23   0.22      2.19
marketRepaySum                         0.00   1.31   0.19      2.40
sinTimeOfDay                           0.00  -8.67 <0.005     57.67
userBorrowSumUSD                       0.00 -30.39 <0.005    671.36
cosTimeOfDay                           0.00  -7.04 <0.005     38.96
cosDayOfWeek                           0.00   6.65 <0.005     34.97
marketWithdrawAvgAmountUSD             0.00  -1.93   0.05      4.22
marketLiquidationSumUSD                0.00  -0.97   0.33      1.58
userDepositAvgAmount                   0.00 -18.80 <0.005    259.40
sinDayOfYear                           0.00   4.04 <0.005     14.22
userDepositCount                       0.00 -29.50 <0.005    632.91
cosDayOfYear                           0.00  -9.59 <0.005     70.00
logAmount                              0.00  27.51 <0.005    551.10
sinDayOfWeek                           0.00   2.27   0.02      5.43
userBorrowAvgAmountUSD                 0.00 -49.27 <0.005       inf
userSecondsSincePreviousTransaction    0.00 -13.34 <0.005    132.52
marketBorrowSumUSD                     0.00  -0.63   0.53      0.92
userRepaySum                           0.00 -30.08 <0.005    658.12
logAmountUSD                           0.00  40.36 <0.005       inf
marketDepositCount                     0.00 -17.12 <0.005    215.85
marketRepayAvgAmountUSD                0.00  -6.82 <0.005     36.71
sinQuarter                             0.00   1.24   0.21      2.22
marketLiquidationAvgAmount             0.00   0.27   0.79      0.34
---
Concordance = 0.80
Partial AIC = 4538077.05
log-likelihood ratio test = 143465.20 on 78 df
-log2(p) of ll-ratio test = inf

In [55]:
# from lifelines.utils import concordance_index

# train_risk = model.predict_partial_hazard(X_train)

# # --- c-index using partial hazard as risk scores ---
# c_index = concordance_index(
#     df_balanced["timeDiff"],       # observed times
#     -train_risk,                   # negative because higher risk -> shorter survival
#     df_balanced["status"]          # event indicator
# )
# print(f"C-Index: {c_index:.3f}")

In [ ]:
model.print_summary()

In [5]:
# from lassonet import LassoNetCoxRegressor

# model = LassoNetCoxRegressor(tie_approximation="breslow")

# X_np = X_train.values if hasattr(X_train, "values") else X_train
# y_np = y_train.values if hasattr(y_train, "values") else y_train

# oracle, order, wrong, paths, prob = model.stability_selection(X_np, y_np)

In [7]:
# order

In [16]:
order = [7, 69, 53, 45,  6, 19, 65, 73,  2, 36, 74, 26, 42, 43,  3, 52,  4, 67,
        17,  8, 37, 64, 38, 21, 39,  9,  1, 35, 31, 66, 28, 14, 30, 76, 13, 70,
        40, 33, 24, 23, 15, 49, 50, 55, 27, 34, 16,  0, 12, 61, 20, 18, 48, 29,
        77, 62, 44, 51, 47, 46, 72, 58, 41, 56, 10, 75, 63, 22, 11, 25, 71, 60,
        68, 32, 54, 59,  5, 57]

print(len(order))

78

In [11]:
columns = (lifelines_train_df.keys()).to_list()

In [19]:
# --- select the columns whose index is in order ---
selected_cols = ["timeDiff", "status"]
for i in order:
    selected_cols.append(columns[i])

print(len(selected_cols))

80

In [20]:
new_lifelines_train_df = lifelines_train_df[selected_cols]
new_lifelines_train_df.head()

,timeDiff,status,userLiquidationCount,userBorrowAvgAmountUSD,userBorrowCount,userLiquidationAvgAmount,userActiveDaysWeekly,userLiquidationSumUSD,userDepositCount,logAmountUSD,...,marketRepayAvgAmount,quarter,marketBorrowSumUSD,cosDayOfWeek,sinDayOfWeek,dayOfMonth,dayOfWeek,cosTimeOfDay,timeOfDay,sinTimeOfDay
0,75264503.0,0.0,-0.156334,-0.485221,-0.439298,-0.075548,-0.396655,-0.0872,-0.237205,-1.254174,...,-2.342678,-1.452898,-1.733569,0.978175,1.050891,-0.185892,-1.448052,-0.743173,-0.570639,1.148620
1,75091115.0,0.0,-0.156334,-0.485246,-0.439298,-0.075548,-1.190754,-0.0872,-0.239892,-1.382937,...,-2.342678,-1.452898,-1.733569,-1.183281,0.557057,0.043339,-0.420731,-0.788563,-0.545239,1.108079
2,75084884.0,0.0,-0.156334,-0.485221,-0.439298,-0.075548,-1.190754,-0.0872,-0.239892,-1.254154,...,-2.342678,-1.452898,-1.733569,-1.183281,0.557057,0.043339,-0.420731,-1.148216,-0.276081,0.575966
3,75084844.0,0.0,-0.156334,-0.485158,-0.439211,-0.075548,-1.190754,-0.0872,-0.239892,-0.977241,...,-2.342678,-1.452898,-1.733569,-1.183281,0.557057,0.043339,-0.420731,-1.149720,-0.274353,0.572074
4,75079718.0,0.0,-0.156334,-0.485227,-0.439298,-0.075548,-1.190754,-0.0872,-0.239892,-1.281682,...,-2.342678,-1.452898,-1.733569,-1.183281,0.557057,0.043339,-0.420731,-1.246935,-0.052927,0.048505

In [21]:
model = CoxPHFitter(penalizer=0.1)
model.fit(new_lifelines_train_df, duration_col='timeDiff', event_col='status')

In [24]:
# model.print_summary()
from lifelines.utils import concordance_index

train_risk = model.predict_partial_hazard(X_train)

# --- c-index using partial hazard as risk scores ---
c_index = concordance_index(
    lifelines_train_df["timeDiff"],       # observed times
    -train_risk,                          # negative because higher risk -> shorter survival
    lifelines_train_df["status"]          # event indicator
)
print(f"C-Index: {c_index:.3f}")

C-Index: 0.814

In [25]:
summary_df = model.summary
summary_df.head()

,coef,exp(coef),se(coef),coef lower 95%,coef upper 95%,exp(coef) lower 95%,exp(coef) upper 95%,cmp to,z,p,-log2(p)
covariate,,,,,,,,,,,
userLiquidationCount,0.178409,1.195314,0.002239,0.174020,0.182798,1.190080,1.200571,0.0,79.676038,0.000000e+00,inf
userBorrowAvgAmountUSD,-0.057935,0.943711,0.003265,-0.064335,-0.051536,0.937691,0.949770,0.0,-17.743118,1.948171e-70,231.572846
userBorrowCount,-0.047917,0.953213,0.003264,-0.054315,-0.041519,0.947134,0.959331,0.0,-14.678561,8.844718e-49,159.629660
userLiquidationAvgAmount,0.033026,1.033577,0.002519,0.028089,0.037963,1.028487,1.038692,0.0,13.111070,2.845553e-39,128.046487
userActiveDaysWeekly,0.062299,1.064281,0.003093,0.056237,0.068361,1.057848,1.070752,0.0,20.142015,3.162034e-90,297.312675